Add Python Kafka pipelines for read/write
GoogleCloudPlatform/dataflow-cookbook pull request #14
Opened 2023-11-21 10:21 UTC by Amar3tto

2023-12-07 14:56 UTC, johnjcasey requested changes

2023-12-07 14:56 UTC, johnjcasey commented on Python/kafka/write_kafka.py
> +                        .with_output_types(typing.Tuple[bytes, bytes])  # Kafka write transforms expects KVs.
it would probably be better to not pre-encode these as bytes.

2023-12-13 19:19 UTC, johnjcasey approved these changes

2023-12-14 22:22 UTC, liferoad commented
Please fix the format and lint errors.

2023-12-19 15:33 UTC, merged